
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  config: classpath:log4j2.xml

spring:
  application:
    name: ferrari-gateway
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1.0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ferrari-auth
          uri: lb://ferrari-auth
          predicates:
            - Path=/ferrari-auth/** # 如果请求地址满足/ferrari-auth/**,则转发到 ferrari-auth 服务
          filters:
            - StripPrefix=1 # 去除请求地址中的ferrari-auth